/**
 * Known aliases for country names that should be accepted as correct answers.
 * Keys are lowercase allowed aliases; values are lowercase correct names.
 */
export const CountryAliases: Record<string, string> = {
  usa: "united states",
  us: "united states",
  america: "united states",
  "united states of america": "united states",
  "us of a": "united states",
  uk: "united kingdom",
  "great britain": "united kingdom",
  gb: "united kingdom",
  uae: "united arab emirates",
  drc: "dr congo",
  congo: "republic of the congo",
  "republic of congo": "republic of the congo",
  "dr congo": "democratic republic of the congo",
  "democratic republic of congo": "democratic republic of the congo",
  "republic of ireland": "ireland",
  "czech republic": "czechia",
  czech: "czechia",
  "ivory coast": "côte d'ivoire",
  "cote divoire": "côte d'ivoire",
  "cote d'ivoire": "côte d'ivoire",
  "republic of korea": "south korea",
  dprk: "north korea",
  "russian federation": "russia",
  "cape verde": "cabo verde",
  swaziland: "eswatini",
  turkiye: "türkiye",
  turkey: "türkiye",
  "republic of turkey": "türkiye",
  "republic of türkiye": "türkiye",
  burma: "myanmar",
  "timor leste": "timor-leste",
  "east timor": "timor-leste",
  trinidad: "trinidad and tobago",
  tobago: "trinidad and tobago",
  "trinidad & tobago": "trinidad and tobago",
  "st lucia": "saint lucia",
  skn: "saint kitts and nevis",
  "saint kitts": "saint kitts and nevis",
  "st kitts": "saint kitts and nevis",
  "st kitts and nevis": "saint kitts and nevis",
  "saint kitts & nevis": "saint kitts and nevis",
  "st kitts & nevis": "saint kitts and nevis",
  "st vincent and the grenadines": "saint vincent and the grenadines",
  "st vincent & the grenadines": "saint vincent and the grenadines",
  "st vincent & grenadines": "saint vincent and the grenadines",
  svg: "saint vincent and the grenadines",
  "são tomé": "são tomé and príncipe",
  "são tomé & príncipe": "são tomé and príncipe",
  "sao tome": "são tomé and príncipe",
  "sao tome and principe": "são tomé and príncipe",
  "sao tome & principe": "são tomé and príncipe",
  "republic of china": "taiwan",
  "west bank": "palestine",
  "plurinational state of bolivia": "bolivia",
  "bolivarian republic of venezuela": "venezuela",
  "islamic republic of iran": "iran",
  macedonia: "north macedonia",
  lao: "laos",
  bahamas: "the bahamas",
  gambia: "the gambia",
  "republic of moldova": "moldova",
  "federated states of micronesia": "micronesia",
  "antigua & barbuda": "antigua and barbuda",
  antigua: "antigua and barbuda",
  "bosnia & herzegovina": "bosnia and herzegovina",
  bosnia: "bosnia and herzegovina",
  "brunei darussalam": "brunei",
  car: "central african republic",
  prc: "china",
  "people's republic of china": "china",
  "peoples republic of china": "china",
  "guinea bissau": "guinea-bissau",
  holland: "netherlands",
  "the netherlands": "netherlands",
  "the philippines": "philippines",
  saudi: "saudi arabia",
  ksa: "saudi arabia",
  "kingdom of saudi arabia": "saudi arabia",
  rsa: "south africa",
  "republic of south africa": "south africa",
  vatican: "vatican city",
  "holy see": "vatican city",
};
